<?php

define( 'TECHLINK_CORE_VERSION', '1.1' );
define( 'TECHLINK_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'TECHLINK_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'TECHLINK_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'TECHLINK_CORE_ASSETS_PATH', TECHLINK_CORE_ABS_PATH . '/assets' );
define( 'TECHLINK_CORE_ASSETS_URL_PATH', TECHLINK_CORE_URL_PATH . 'assets' );
define( 'TECHLINK_CORE_INC_PATH', TECHLINK_CORE_ABS_PATH . '/inc' );
define( 'TECHLINK_CORE_INC_URL_PATH', TECHLINK_CORE_URL_PATH . 'inc' );
define( 'TECHLINK_CORE_CPT_PATH', TECHLINK_CORE_INC_PATH . '/post-types' );
define( 'TECHLINK_CORE_CPT_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/post-types' );
define( 'TECHLINK_CORE_SHORTCODES_PATH', TECHLINK_CORE_INC_PATH . '/shortcodes' );
define( 'TECHLINK_CORE_SHORTCODES_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/shortcodes' );
define( 'TECHLINK_CORE_PLUGINS_PATH', TECHLINK_CORE_INC_PATH . '/plugins' );
define( 'TECHLINK_CORE_PLUGINS_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/plugins' );
define( 'TECHLINK_CORE_HEADER_LAYOUTS_PATH', TECHLINK_CORE_INC_PATH . '/header/layouts' );
define( 'TECHLINK_CORE_HEADER_LAYOUTS_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/header/layouts' );
define( 'TECHLINK_CORE_HEADER_ASSETS_PATH', TECHLINK_CORE_INC_PATH . '/header/assets' );
define( 'TECHLINK_CORE_HEADER_ASSETS_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/header/assets' );
define( 'TECHLINK_CORE_MOBILE_HEADER_LAYOUTS_PATH', TECHLINK_CORE_INC_PATH . '/mobile-header/layouts' );
define( 'TECHLINK_CORE_MOBILE_HEADER_LAYOUTS_URL_PATH', TECHLINK_CORE_INC_URL_PATH . '/mobile-header/layouts' );

define( 'TECHLINK_CORE_MENU_NAME', 'techlink_core_menu' );
define( 'TECHLINK_CORE_OPTIONS_NAME', 'techlink_core_options' );

define( 'TECHLINK_CORE_PROFILE_SLUG', 'mikado' );